# Generated by Django 6.0.4 on 2026-05-02 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la playlist')),
                ('description', models.TextField(blank=True, null=True)),
                ('est_publique', models.BooleanField(default=True, verbose_name='Publique')),
                ('pochette', models.ImageField(blank=True, null=True, upload_to='playlists/', verbose_name='Image')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='playlists.playlist', verbose_name='Playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='music.song', verbose_name='Chanson')),
            ],
            options={
                'verbose_name': 'Item de Playlist',
                'verbose_name_plural': 'Items de Playlist',
                'ordering': ['ordre', 'date_ajout'],
                'unique_together': {('playlist', 'song')},
            },
        ),
    ]
