# data.py - Liste de musiques pour Sosie Spotify
# Equivalent du data.py produits de l'atelier, adapte pour la musique

musics = [
    {
        'id': 1,
        'titre': 'Blinding Lights',
        'artiste': 'The Weeknd',
        'album': 'After Hours',
        'genre': 'Pop',
        'duree': '3:20',
        'annee': 2019,
        'cover': 'https://upload.wikimedia.org/wikipedia/en/e/e6/The_Weeknd_-_Blinding_Lights.png',
    },
    {
        'id': 2,
        'titre': 'Shape of You',
        'artiste': 'Ed Sheeran',
        'album': '÷ (Divide)',
        'genre': 'Pop',
        'duree': '3:54',
        'annee': 2017,
        'cover': 'https://upload.wikimedia.org/wikipedia/en/3/35/Shape_of_You_%28Official_Single_Cover%29_by_Ed_Sheeran.png',
    },
    {
        'id': 3,
        'titre': 'Bohemian Rhapsody',
        'artiste': 'Queen',
        'album': 'A Night at the Opera',
        'genre': 'Rock',
        'duree': '5:55',
        'annee': 1975,
        'cover': 'https://upload.wikimedia.org/wikipedia/en/9/9f/Bohemian_Rhapsody.png',
    },
    {
        'id': 4,
        'titre': 'Levitating',
        'artiste': 'Dua Lipa',
        'album': 'Future Nostalgia',
        'genre': 'Pop',
        'duree': '3:23',
        'annee': 2020,
        'cover': 'https://upload.wikimedia.org/wikipedia/en/3/39/Dua_Lipa_-_Levitating_Featuring_DaBaby.png',
    },
    {
        'id': 5,
        'titre': 'Stay With Me',
        'artiste': 'Sam Smith',
        'album': 'In the Lonely Hour',
        'genre': 'Soul',
        'duree': '2:52',
        'annee': 2014,
        'cover': 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6c/Sam_Smith_Stay_With_Me.jpg/220px-Sam_Smith_Stay_With_Me.jpg',
    },
    {
        'id': 6,
        'titre': 'Flowers',
        'artiste': 'Miley Cyrus',
        'album': 'Endless Summer Vacation',
        'genre': 'Pop',
        'duree': '3:20',
        'annee': 2023,
        'cover': 'https://upload.wikimedia.org/wikipedia/en/a/ab/Miley_Cyrus_-_Flowers.png',
    },
    {
        'id': 7,
        'titre': 'As It Was',
        'artiste': 'Harry Styles',
        'album': "Harry's House",
        'genre': 'Pop',
        'duree': '2:37',
        'annee': 2022,
        'cover': 'https://upload.wikimedia.org/wikipedia/en/d/d6/Harry_Styles_-_As_It_Was.png',
    },
    {
        'id': 8,
        'titre': 'Anti-Hero',
        'artiste': 'Taylor Swift',
        'album': 'Midnights',
        'genre': 'Pop',
        'duree': '3:21',
        'annee': 2022,
        'cover': 'https://upload.wikimedia.org/wikipedia/en/1/1f/Taylor_Swift_-_Anti-Hero_%28single%29.png',
    },
]
