# Generated by Django 6.0.4 on 2026-05-02 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'artiste")),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biographie')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='artistes/', verbose_name='Photo')),
                ('pays', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Artiste',
                'verbose_name_plural': 'Artistes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Genre')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'album")),
                ('pochette', models.ImageField(blank=True, null=True, upload_to='albums/', verbose_name='Pochette')),
                ('annee_sortie', models.IntegerField(blank=True, null=True, verbose_name='Année de sortie')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('artiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music.artiste', verbose_name='Artiste')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'ordering': ['-annee_sortie'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('fichier_audio', models.FileField(blank=True, null=True, upload_to='songs/', verbose_name='Fichier audio (MP3)')),
                ('duree', models.IntegerField(default=0, verbose_name='Durée (secondes)')),
                ('nb_ecoutes', models.IntegerField(default=0, verbose_name="Nombre d'écoutes")),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='music.album', verbose_name='Album')),
                ('artiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.artiste', verbose_name='Artiste')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='music.genre', verbose_name='Genre')),
            ],
            options={
                'verbose_name': 'Chanson',
                'verbose_name_plural': 'Chansons',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
