# Generated by Django 6.0.4 on 2026-05-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='pochette',
            field=models.ImageField(blank=True, null=True, upload_to='songs/pochettes/', verbose_name='Pochette de la chanson'),
        ),
    ]
